<?php

define("DB_TABLE", "IN_LOWER_CASE_PUT_YOUR_DB_TABLE_NAME");
define("DB_USER", "IN_LOWER_CASE_PUT_YOUR_DB_USER");
define("DB_PASSWORD", "IN_LOWER_CASE_PUT_YOUR_PASSWORD");
define("DB_HOST", "IN_LOWER_CASE_PUT_YOUR_HOST");

define("SITE_URL", "IN_LOWER_CASE_PUT_SITE_URL");
define("AWS_SES_EMAIL", "IN_LOWER_CASE_PUT_SES_EMAIL");
define("AWS_U_NAME", "IN_LOWER_CASE_PUT_AWS_USERNAME");
define("AWS_SES_PASSWORD", "IN_LOWER_CASE_PUT_SES_PASSWORD");
define("IMAGE_URL", "IN_LOWER_CASE_PUT_S3_URL_TO_IMAGE");

//PP_LIVE
define('PP_CLIENT_ID', 'IN_LOWER_CASE_PUT_PAYPAL_CLIENT_ID');
define('PP_CLIENT_SECRET', 'IN_LOWER_CASE_PUT_PAYPAL_SECRET_KEY');

//PP_DEV
define('PP_CLIENT_DEV_ID', 'IN_LOWER_CASE_PUT_PP_CLIENT_DEV_ID');
define('PP_CLIENT_DEV_SECRET', 'IN_LOWER_CASE_PUT_PP_CLIENT_DEV_SECRET');
 
define('PAYPAL_RETURN_URL', 'IN_LOWER_CASE_PUT_PAYPAL_RETURN_URL');
define('PAYPAL_CANCEL_URL', 'IN_LOWER_CASE_PUT_PAYPAL_CANCEL_URL');
define('PAYPAL_CURRENCY', 'USD');

define('STRIPE_DEV_KEY', 'IN_LOWER_CASE_PUT_STRIPE_DEV_KEY');
define('STRIPE_DEV_SECRET', 'IN_LOWER_CASE_PUT_STRIPE_DEV_SECRET');

define('STRIPE_LIVE_KEY', 'IN_LOWER_CASESTRIPE_LIVE_KEY');
define('STRIPE_LIVE_SECRET','IN_LOWER_CASESTRIPE_SECRET_KEY');

define ('S3_KEY','S3_KEY');
define ('S3_SECRET','S3_SECRET');

?>